member: fix ISO C in exported header
[ upstream commit 34c709f9b21cc5bc9bad338e908ebca08a6dfc37 ]

Reported by check-includes.sh:

 [...]/rte_member.h:107:40: error: ISO C does not permit named variadic
     macros [-Werror=variadic-macros]
  #define RTE_MEMBER_LOG(level, fmt, args...) \
                                         ^

Fixes: 857ed6c68cf2 ("member: implement main API")

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>