Revert "net/mlx5: fix flex item availability"
This reverts commit 48fe9efaf2fb974e3f805eb7c54440ec3818a4b6.

This patch seems to be causing a build failure [0] in the CI [1] with
meson on Windows.

Revert for now and it can be reapplied at a later time when it is fixed.

[0]
[531/617] Compiling C object
drivers/a715181@@tmp_rte_net_mlx5@sta/net_mlx5_mlx5_flow.c.obj.
FAILED: drivers/a715181@@tmp_rte_net_mlx5@sta/net_mlx5_mlx5_flow.c.obj
clang @drivers/a715181@@tmp_rte_net_mlx5@sta/net_mlx5_mlx5_flow.c.obj.rsp
../drivers/net/mlx5/mlx5_flow.c:9867:23: error: incomplete definition of
type 'struct rte_pci_device'
         switch (priv->pci_dev->id.device_id) {
                 ~~~~~~~~~~~~~^
..\drivers\net/mlx5/mlx5.h:154:9: note: forward declaration of 'struct
rte_pci_device'
         struct rte_pci_device *pci_dev; /**< Backend PCI device. */
                ^
1 error generated.

[1]
https://lab.dpdk.org/results/dashboard/tarballs/19198/#env-27

Cc: rasland@nvidia.com
Cc: getelson@nvidia.com
Cc: viacheslavo@nvidia.com
Signed-off-by: Kevin Traynor <ktraynor@redhat.com>