PVT:event/dpaa: fix include header
rte_cycles.h shall be included instead of rte_cycles_64.h

dpaa_eventdev.c:32:27:
fatal error: rte_cycles_64.h: No such file or directory

Fixes: 5039e023fbf4 ("event/dpaa: add eventdev PMD")

Signed-off-by: Hemant Agrawal <hemant.agrawal@nxp.com>