buildtools: Remove class_id from rte_pci_id
This pacth is used to fix the build error pasted below:

No idea where does the "8 bytes" come from,
have to remove class_id(4 bytes) to decrease size from 12 bytes to 8 bytes.

This build error occures with meson configuration:
meson x86-64-build -Dc_args="-Werror" -Ddpaa2_use_phys_iova=true

Anyone can provide more reasonable fix?

Traceback (most recent call last):
  File "../buildtools/pmdinfogen.py", line 274, in <module>
    main()
  File "../buildtools/pmdinfogen.py", line 269, in main
    drivers = load_drivers(image)
  File "../buildtools/pmdinfogen.py", line 203, in load_drivers
    drivers.append(Driver.load(image, symbol))
  File "../buildtools/pmdinfogen.py", line 157, in load
    driver.pci_ids = cls._load_pci_ids(image, pci_table_name_symbol)
  File "../buildtools/pmdinfogen.py", line 177, in _load_pci_ids
    pci_id = rte_pci_id.from_buffer_copy(data)
ValueError: Buffer size too small (8 instead of at least 12 bytes)
Traceback (most recent call last):
  File "../buildtools/gen-pmdinfo-cfile.py", line 21, in <module>
    subprocess.run(pmdinfogen + paths + [output], check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,

Signed-off-by: Jun Yang <jun.yang@nxp.com>