net/lsxinic: move bd size functions to common helper
it was causing compilation issue when placed in common_reg

lsxinic/lsxinic_common_reg.h:654:18: error: implicit declaration of function ‘rte_align64pow2’

Signed-off-by: Hemant Agrawal <hemant.agrawal@nxp.com>